# Replace this with your own database configuration.

development:
  adapter: mysql
  database: blog_development
  username: root
  password:
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  database: blog_test
  username: root
  password:
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: blog_production
  username: root
  password: 
  host: localhost
