# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "comments", :force => true do |t|
    t.column "user_id",    :integer
    t.column "content",    :text,     :default => "",                    :null => false
    t.column "created_at", :datetime
    t.column "post_id",    :integer
    t.column "updated_at", :datetime, :default => '2007-09-03 22:42:42'
  end

  create_table "posts", :force => true do |t|
    t.column "title",      :string,   :default => "", :null => false
    t.column "content",    :text,     :default => "", :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "posts_tags", :id => false, :force => true do |t|
    t.column "post_id", :integer
    t.column "tag_id",  :integer
  end

  add_index "posts_tags", ["post_id"], :name => "index_posts_tags_on_post_id"
  add_index "posts_tags", ["tag_id"], :name => "index_posts_tags_on_tag_id"

  create_table "tags", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "users", :force => true do |t|
    t.column "name",      :string,  :default => "",    :null => false
    t.column "admin",     :boolean, :default => false
    t.column "email",     :string
    t.column "link",      :string
    t.column "pass_hash", :string
    t.column "salt",      :string
    t.column "ip",        :string
    t.column "agent",     :string
    t.column "referrer",  :string
  end

end
